version: '3.3'
services:
  mysql-server:
    container_name: mysql-server
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${APP_DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '${APP_DB_PORT}:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - dbdata:/var/lib/mysql
# Names our volume
volumes:
  dbdata: